<?php

namespace Database\Seeders\Masters;

use App\Models\Masters\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Index 0 - The Boss
            ['name' => 'India', 'slug' => 'india', 'phone_code' => '+91', 'iso_code' => 'IN'],

            // The Rest 49
            ['name' => 'United States', 'slug' => 'united-states', 'phone_code' => '+1', 'iso_code' => 'US'],
            ['name' => 'United Kingdom', 'slug' => 'united-kingdom', 'phone_code' => '+44', 'iso_code' => 'GB'],
            ['name' => 'Canada', 'slug' => 'canada', 'phone_code' => '+1', 'iso_code' => 'CA'],
            ['name' => 'Australia', 'slug' => 'australia', 'phone_code' => '+61', 'iso_code' => 'AU'],
            ['name' => 'Germany', 'slug' => 'germany', 'phone_code' => '+49', 'iso_code' => 'DE'],
            ['name' => 'France', 'slug' => 'france', 'phone_code' => '+33', 'iso_code' => 'FR'],
            ['name' => 'Japan', 'slug' => 'japan', 'phone_code' => '+81', 'iso_code' => 'JP'],
            ['name' => 'China', 'slug' => 'china', 'phone_code' => '+86', 'iso_code' => 'CN'],
            ['name' => 'Brazil', 'slug' => 'brazil', 'phone_code' => '+55', 'iso_code' => 'BR'],
            ['name' => 'South Africa', 'slug' => 'south-africa', 'phone_code' => '+27', 'iso_code' => 'ZA'],
            ['name' => 'Russia', 'slug' => 'russia', 'phone_code' => '+7', 'iso_code' => 'RU'],
            ['name' => 'Mexico', 'slug' => 'mexico', 'phone_code' => '+52', 'iso_code' => 'MX'],
            ['name' => 'Italy', 'slug' => 'italy', 'phone_code' => '+39', 'iso_code' => 'IT'],
            ['name' => 'Spain', 'slug' => 'spain', 'phone_code' => '+34', 'iso_code' => 'ES'],
            ['name' => 'United Arab Emirates', 'slug' => 'united-arab-emirates', 'phone_code' => '+971', 'iso_code' => 'AE'],
            ['name' => 'Saudi Arabia', 'slug' => 'saudi-arabia', 'phone_code' => '+966', 'iso_code' => 'SA'],
            ['name' => 'Singapore', 'slug' => 'singapore', 'phone_code' => '+65', 'iso_code' => 'SG'],
            ['name' => 'New Zealand', 'slug' => 'new-zealand', 'phone_code' => '+64', 'iso_code' => 'NZ'],
            ['name' => 'Nepal', 'slug' => 'nepal', 'phone_code' => '+977', 'iso_code' => 'NP'],
            ['name' => 'Sri Lanka', 'slug' => 'sri-lanka', 'phone_code' => '+94', 'iso_code' => 'LK'],
            ['name' => 'Bangladesh', 'slug' => 'bangladesh', 'phone_code' => '+880', 'iso_code' => 'BD'],
            ['name' => 'Pakistan', 'slug' => 'pakistan', 'phone_code' => '+92', 'iso_code' => 'PK'],
            ['name' => 'Indonesia', 'slug' => 'indonesia', 'phone_code' => '+62', 'iso_code' => 'ID'],
            ['name' => 'Malaysia', 'slug' => 'malaysia', 'phone_code' => '+60', 'iso_code' => 'MY'],
            ['name' => 'Philippines', 'slug' => 'philippines', 'phone_code' => '+63', 'iso_code' => 'PH'],
            ['name' => 'Vietnam', 'slug' => 'vietnam', 'phone_code' => '+84', 'iso_code' => 'VN'],
            ['name' => 'Thailand', 'slug' => 'thailand', 'phone_code' => '+66', 'iso_code' => 'TH'],
            ['name' => 'South Korea', 'slug' => 'south-korea', 'phone_code' => '+82', 'iso_code' => 'KR'],
            ['name' => 'Turkey', 'slug' => 'turkey', 'phone_code' => '+90', 'iso_code' => 'TR'],
            ['name' => 'Egypt', 'slug' => 'egypt', 'phone_code' => '+20', 'iso_code' => 'EG'],
            ['name' => 'Nigeria', 'slug' => 'nigeria', 'phone_code' => '+234', 'iso_code' => 'NG'],
            ['name' => 'Kenya', 'slug' => 'kenya', 'phone_code' => '+254', 'iso_code' => 'KE'],
            ['name' => 'Argentina', 'slug' => 'argentina', 'phone_code' => '+54', 'iso_code' => 'AR'],
            ['name' => 'Colombia', 'slug' => 'colombia', 'phone_code' => '+57', 'iso_code' => 'CO'],
            ['name' => 'Chile', 'slug' => 'chile', 'phone_code' => '+56', 'iso_code' => 'CL'],
            ['name' => 'Peru', 'slug' => 'peru', 'phone_code' => '+51', 'iso_code' => 'PE'],
            ['name' => 'Netherlands', 'slug' => 'netherlands', 'phone_code' => '+31', 'iso_code' => 'NL'],
            ['name' => 'Switzerland', 'slug' => 'switzerland', 'phone_code' => '+41', 'iso_code' => 'CH'],
            ['name' => 'Sweden', 'slug' => 'sweden', 'phone_code' => '+46', 'iso_code' => 'SE'],
            ['name' => 'Norway', 'slug' => 'norway', 'phone_code' => '+47', 'iso_code' => 'NO'],
            ['name' => 'Denmark', 'slug' => 'denmark', 'phone_code' => '+45', 'iso_code' => 'DK'],
            ['name' => 'Finland', 'slug' => 'finland', 'phone_code' => '+358', 'iso_code' => 'FI'],
            ['name' => 'Ireland', 'slug' => 'ireland', 'phone_code' => '+353', 'iso_code' => 'IE'],
            ['name' => 'Portugal', 'slug' => 'portugal', 'phone_code' => '+351', 'iso_code' => 'PT'],
            ['name' => 'Greece', 'slug' => 'greece', 'phone_code' => '+30', 'iso_code' => 'GR'],
            ['name' => 'Poland', 'slug' => 'poland', 'phone_code' => '+48', 'iso_code' => 'PL'],
            ['name' => 'Ukraine', 'slug' => 'ukraine', 'phone_code' => '+380', 'iso_code' => 'UA'],
            ['name' => 'Israel', 'slug' => 'israel', 'phone_code' => '+972', 'iso_code' => 'IL'],
            ['name' => 'Qatar', 'slug' => 'qatar', 'phone_code' => '+974', 'iso_code' => 'QA'],
            ['name' => 'Austria', 'slug' => 'austria', 'phone_code' => '+43', 'iso_code' => 'AT'],
            ['name' => 'Belgium', 'slug' => 'belgium', 'phone_code' => '+32', 'iso_code' => 'BE'],
            ['name' => 'Czech Republic', 'slug' => 'czech-republic', 'phone_code' => '+420', 'iso_code' => 'CZ'],
            ['name' => 'Hungary', 'slug' => 'hungary', 'phone_code' => '+36', 'iso_code' => 'HU'],
            ['name' => 'Romania', 'slug' => 'romania', 'phone_code' => '+40', 'iso_code' => 'RO'],
            ['name' => 'Bulgaria', 'slug' => 'bulgaria', 'phone_code' => '+359', 'iso_code' => 'BG'],
            ['name' => 'Serbia', 'slug' => 'serbia', 'phone_code' => '+381', 'iso_code' => 'RS'],
            ['name' => 'Croatia', 'slug' => 'croatia', 'phone_code' => '+385', 'iso_code' => 'HR'],
            ['name' => 'Slovakia', 'slug' => 'slovakia', 'phone_code' => '+421', 'iso_code' => 'SK'],
            ['name' => 'Belarus', 'slug' => 'belarus', 'phone_code' => '+375', 'iso_code' => 'BY'],
            ['name' => 'Iran', 'slug' => 'iran', 'phone_code' => '+98', 'iso_code' => 'IR'],
            ['name' => 'Iraq', 'slug' => 'iraq', 'phone_code' => '+964', 'iso_code' => 'IQ'],
            ['name' => 'Afghanistan', 'slug' => 'afghanistan', 'phone_code' => '+93', 'iso_code' => 'AF'],
            ['name' => 'Syria', 'slug' => 'syria', 'phone_code' => '+963', 'iso_code' => 'SY'],
            ['name' => 'Jordan', 'slug' => 'jordan', 'phone_code' => '+962', 'iso_code' => 'JO'],
            ['name' => 'Lebanon', 'slug' => 'lebanon', 'phone_code' => '+961', 'iso_code' => 'LB'],
            ['name' => 'Oman', 'slug' => 'oman', 'phone_code' => '+968', 'iso_code' => 'OM'],
            ['name' => 'Kuwait', 'slug' => 'kuwait', 'phone_code' => '+965', 'iso_code' => 'KW'],
            ['name' => 'Bahrain', 'slug' => 'bahrain', 'phone_code' => '+973', 'iso_code' => 'BH'],
            ['name' => 'Taiwan', 'slug' => 'taiwan', 'phone_code' => '+886', 'iso_code' => 'TW'],
            ['name' => 'Kazakhstan', 'slug' => 'kazakhstan', 'phone_code' => '+7', 'iso_code' => 'KZ'],
            ['name' => 'Uzbekistan', 'slug' => 'uzbekistan', 'phone_code' => '+998', 'iso_code' => 'UZ'],
            ['name' => 'Myanmar', 'slug' => 'myanmar', 'phone_code' => '+95', 'iso_code' => 'MM'],
            ['name' => 'Cambodia', 'slug' => 'cambodia', 'phone_code' => '+855', 'iso_code' => 'KH'],
            ['name' => 'Venezuela', 'slug' => 'venezuela', 'phone_code' => '+58', 'iso_code' => 'VE'],
            ['name' => 'Ecuador', 'slug' => 'ecuador', 'phone_code' => '+593', 'iso_code' => 'EC'],
            ['name' => 'Bolivia', 'slug' => 'bolivia', 'phone_code' => '+591', 'iso_code' => 'BO'],
            ['name' => 'Paraguay', 'slug' => 'paraguay', 'phone_code' => '+595', 'iso_code' => 'PY'],
            ['name' => 'Uruguay', 'slug' => 'uruguay', 'phone_code' => '+598', 'iso_code' => 'UY'],
            ['name' => 'Cuba', 'slug' => 'cuba', 'phone_code' => '+53', 'iso_code' => 'CU'],
            ['name' => 'Dominican Republic', 'slug' => 'dominican-republic', 'phone_code' => '+1', 'iso_code' => 'DO'],
            ['name' => 'Costa Rica', 'slug' => 'costa-rica', 'phone_code' => '+506', 'iso_code' => 'CR'],
            ['name' => 'Panama', 'slug' => 'panama', 'phone_code' => '+507', 'iso_code' => 'PA'],
            ['name' => 'Jamaica', 'slug' => 'jamaica', 'phone_code' => '+1', 'iso_code' => 'JM'],
            ['name' => 'Morocco', 'slug' => 'morocco', 'phone_code' => '+212', 'iso_code' => 'MA'],
            ['name' => 'Algeria', 'slug' => 'algeria', 'phone_code' => '+213', 'iso_code' => 'DZ'],
            ['name' => 'Ethiopia', 'slug' => 'ethiopia', 'phone_code' => '+251', 'iso_code' => 'ET'],
            ['name' => 'Ghana', 'slug' => 'ghana', 'phone_code' => '+233', 'iso_code' => 'GH'],
            ['name' => 'Tanzania', 'slug' => 'tanzania', 'phone_code' => '+255', 'iso_code' => 'TZ'],
            ['name' => 'Uganda', 'slug' => 'uganda', 'phone_code' => '+256', 'iso_code' => 'UG'],
            ['name' => 'Angola', 'slug' => 'angola', 'phone_code' => '+244', 'iso_code' => 'AO'],
            ['name' => 'Mozambique', 'slug' => 'mozambique', 'phone_code' => '+258', 'iso_code' => 'MZ'],
            ['name' => 'Ivory Coast', 'slug' => 'ivory-coast', 'phone_code' => '+225', 'iso_code' => 'CI'],
            ['name' => 'Cameroon', 'slug' => 'cameroon', 'phone_code' => '+237', 'iso_code' => 'CM'],
            ['name' => 'Senegal', 'slug' => 'senegal', 'phone_code' => '+221', 'iso_code' => 'SN'],
            ['name' => 'Zimbabwe', 'slug' => 'zimbabwe', 'phone_code' => '+263', 'iso_code' => 'ZW'],
            ['name' => 'Fiji', 'slug' => 'fiji', 'phone_code' => '+679', 'iso_code' => 'FJ'],
            ['name' => 'Papua New Guinea', 'slug' => 'papua-new-guinea', 'phone_code' => '+675', 'iso_code' => 'PG'],
            ['name' => 'Iceland', 'slug' => 'iceland', 'phone_code' => '+354', 'iso_code' => 'IS'],
            ['name' => 'Cyprus', 'slug' => 'cyprus', 'phone_code' => '+357', 'iso_code' => 'CY'],
            ['name' => 'Estonia', 'slug' => 'estonia', 'phone_code' => '+372', 'iso_code' => 'EE'],
            ['name' => 'Latvia', 'slug' => 'latvia', 'phone_code' => '+371', 'iso_code' => 'LV'],
            ['name' => 'Lithuania', 'slug' => 'lithuania', 'phone_code' => '+370', 'iso_code' => 'LT'],
            ['name' => 'Slovenia', 'slug' => 'slovenia', 'phone_code' => '+386', 'iso_code' => 'SI'],
            ['name' => 'Bosnia and Herzegovina', 'slug' => 'bosnia-and-herzegovina', 'phone_code' => '+387', 'iso_code' => 'BA'],
            ['name' => 'North Macedonia', 'slug' => 'north-macedonia', 'phone_code' => '+389', 'iso_code' => 'MK'],
            ['name' => 'Albania', 'slug' => 'albania', 'phone_code' => '+355', 'iso_code' => 'AL'],
            ['name' => 'Montenegro', 'slug' => 'montenegro', 'phone_code' => '+382', 'iso_code' => 'ME'],
            ['name' => 'Malta', 'slug' => 'malta', 'phone_code' => '+356', 'iso_code' => 'MT'],
            ['name' => 'Luxembourg', 'slug' => 'luxembourg', 'phone_code' => '+352', 'iso_code' => 'LU'],
            ['name' => 'Yemen', 'slug' => 'yemen', 'phone_code' => '+967', 'iso_code' => 'YE'],
            ['name' => 'Armenia', 'slug' => 'armenia', 'phone_code' => '+374', 'iso_code' => 'AM'],
            ['name' => 'Azerbaijan', 'slug' => 'azerbaijan', 'phone_code' => '+994', 'iso_code' => 'AZ'],
            ['name' => 'Georgia', 'slug' => 'georgia', 'phone_code' => '+995', 'iso_code' => 'GE'],
            ['name' => 'Turkmenistan', 'slug' => 'turkmenistan', 'phone_code' => '+993', 'iso_code' => 'TM'],
            ['name' => 'Tajikistan', 'slug' => 'tajikistan', 'phone_code' => '+992', 'iso_code' => 'TJ'],
            ['name' => 'Kyrgyzstan', 'slug' => 'kyrgyzstan', 'phone_code' => '+996', 'iso_code' => 'KG'],
            ['name' => 'Mongolia', 'slug' => 'mongolia', 'phone_code' => '+976', 'iso_code' => 'MN'],
            ['name' => 'Maldives', 'slug' => 'maldives', 'phone_code' => '+960', 'iso_code' => 'MV'],
            ['name' => 'Bhutan', 'slug' => 'bhutan', 'phone_code' => '+975', 'iso_code' => 'BT'],
            ['name' => 'Brunei', 'slug' => 'brunei', 'phone_code' => '+673', 'iso_code' => 'BN'],
            ['name' => 'Laos', 'slug' => 'laos', 'phone_code' => '+856', 'iso_code' => 'LA'],
            ['name' => 'Tunisia', 'slug' => 'tunisia', 'phone_code' => '+216', 'iso_code' => 'TN'],
            ['name' => 'Libya', 'slug' => 'libya', 'phone_code' => '+218', 'iso_code' => 'LY'],
            ['name' => 'Sudan', 'slug' => 'sudan', 'phone_code' => '+249', 'iso_code' => 'SD'],
            ['name' => 'Somalia', 'slug' => 'somalia', 'phone_code' => '+252', 'iso_code' => 'SO'],
            ['name' => 'Mali', 'slug' => 'mali', 'phone_code' => '+223', 'iso_code' => 'ML'],
            ['name' => 'Niger', 'slug' => 'niger', 'phone_code' => '+227', 'iso_code' => 'NE'],
            ['name' => 'Chad', 'slug' => 'chad', 'phone_code' => '+235', 'iso_code' => 'TD'],
            ['name' => 'Burkina Faso', 'slug' => 'burkina-faso', 'phone_code' => '+226', 'iso_code' => 'BF'],
            ['name' => 'Guinea', 'slug' => 'guinea', 'phone_code' => '+224', 'iso_code' => 'GN'],
            ['name' => 'Rwanda', 'slug' => 'rwanda', 'phone_code' => '+250', 'iso_code' => 'RW'],
            ['name' => 'Burundi', 'slug' => 'burundi', 'phone_code' => '+257', 'iso_code' => 'BI'],
            ['name' => 'Zambia', 'slug' => 'zambia', 'phone_code' => '+260', 'iso_code' => 'ZM'],
            ['name' => 'Malawi', 'slug' => 'malawi', 'phone_code' => '+265', 'iso_code' => 'MW'],
            ['name' => 'Botswana', 'slug' => 'botswana', 'phone_code' => '+267', 'iso_code' => 'BW'],
            ['name' => 'Namibia', 'slug' => 'namibia', 'phone_code' => '+264', 'iso_code' => 'NA'],
            ['name' => 'Madagascar', 'slug' => 'madagascar', 'phone_code' => '+261', 'iso_code' => 'MG'],
            ['name' => 'Mauritius', 'slug' => 'mauritius', 'phone_code' => '+230', 'iso_code' => 'MU'],
            ['name' => 'Guatemala', 'slug' => 'guatemala', 'phone_code' => '+502', 'iso_code' => 'GT'],
            ['name' => 'Honduras', 'slug' => 'honduras', 'phone_code' => '+504', 'iso_code' => 'HN'],
            ['name' => 'El Salvador', 'slug' => 'el-salvador', 'phone_code' => '+503', 'iso_code' => 'SV'],
            ['name' => 'Nicaragua', 'slug' => 'nicaragua', 'phone_code' => '+505', 'iso_code' => 'NI'],
            ['name' => 'Haiti', 'slug' => 'haiti', 'phone_code' => '+509', 'iso_code' => 'HT'],
            ['name' => 'Bahamas', 'slug' => 'bahamas', 'phone_code' => '+1', 'iso_code' => 'BS'],
            ['name' => 'Trinidad and Tobago', 'slug' => 'trinidad-and-tobago', 'phone_code' => '+1', 'iso_code' => 'TT'],
            ['name' => 'Barbados', 'slug' => 'barbados', 'phone_code' => '+1', 'iso_code' => 'BB'],
            ['name' => 'Guyana', 'slug' => 'guyana', 'phone_code' => '+592', 'iso_code' => 'GY'],
            ['name' => 'Suriname', 'slug' => 'suriname', 'phone_code' => '+597', 'iso_code' => 'SR'],
            ['name' => 'Belize', 'slug' => 'belize', 'phone_code' => '+501', 'iso_code' => 'BZ'],
            // The Final 45 Countries (Batch 4 - Complete 195 List)
            ['name' => 'Andorra', 'slug' => 'andorra', 'phone_code' => '+376', 'iso_code' => 'AD'],
            ['name' => 'San Marino', 'slug' => 'san-marino', 'phone_code' => '+378', 'iso_code' => 'SM'],
            ['name' => 'Monaco', 'slug' => 'monaco', 'phone_code' => '+377', 'iso_code' => 'MC'],
            ['name' => 'Liechtenstein', 'slug' => 'liechtenstein', 'phone_code' => '+423', 'iso_code' => 'LI'],
            ['name' => 'Vatican City', 'slug' => 'vatican-city', 'phone_code' => '+379', 'iso_code' => 'VA'],
            ['name' => 'Moldova', 'slug' => 'moldova', 'phone_code' => '+373', 'iso_code' => 'MD'],
            ['name' => 'Antigua and Barbuda', 'slug' => 'antigua-and-barbuda', 'phone_code' => '+1', 'iso_code' => 'AG'],
            ['name' => 'Saint Kitts and Nevis', 'slug' => 'saint-kitts-and-nevis', 'phone_code' => '+1', 'iso_code' => 'KN'],
            ['name' => 'Saint Lucia', 'slug' => 'saint-lucia', 'phone_code' => '+1', 'iso_code' => 'LC'],
            ['name' => 'Saint Vincent and the Grenadines', 'slug' => 'saint-vincent-and-the-grenadines', 'phone_code' => '+1', 'iso_code' => 'VC'],
            ['name' => 'Grenada', 'slug' => 'grenada', 'phone_code' => '+1', 'iso_code' => 'GD'],
            ['name' => 'Dominica', 'slug' => 'dominica', 'phone_code' => '+1', 'iso_code' => 'DM'],
            ['name' => 'Eswatini', 'slug' => 'eswatini', 'phone_code' => '+268', 'iso_code' => 'SZ'],
            ['name' => 'Lesotho', 'slug' => 'lesotho', 'phone_code' => '+266', 'iso_code' => 'LS'],
            ['name' => 'Seychelles', 'slug' => 'seychelles', 'phone_code' => '+248', 'iso_code' => 'SC'],
            ['name' => 'Comoros', 'slug' => 'comoros', 'phone_code' => '+269', 'iso_code' => 'KM'],
            ['name' => 'Cape Verde', 'slug' => 'cape-verde', 'phone_code' => '+238', 'iso_code' => 'CV'],
            ['name' => 'Sao Tome and Principe', 'slug' => 'sao-tome-and-principe', 'phone_code' => '+239', 'iso_code' => 'ST'],
            ['name' => 'Equatorial Guinea', 'slug' => 'equatorial-guinea', 'phone_code' => '+240', 'iso_code' => 'GQ'],
            ['name' => 'Gabon', 'slug' => 'gabon', 'phone_code' => '+241', 'iso_code' => 'GA'],
            ['name' => 'Republic of the Congo', 'slug' => 'republic-of-the-congo', 'phone_code' => '+242', 'iso_code' => 'CG'],
            ['name' => 'Democratic Republic of the Congo', 'slug' => 'democratic-republic-of-the-congo', 'phone_code' => '+243', 'iso_code' => 'CD'],
            ['name' => 'Central African Republic', 'slug' => 'central-african-republic', 'phone_code' => '+236', 'iso_code' => 'CF'],
            ['name' => 'South Sudan', 'slug' => 'south-sudan', 'phone_code' => '+211', 'iso_code' => 'SS'],
            ['name' => 'Eritrea', 'slug' => 'eritrea', 'phone_code' => '+291', 'iso_code' => 'ER'],
            ['name' => 'Djibouti', 'slug' => 'djibouti', 'phone_code' => '+253', 'iso_code' => 'DJ'],
            ['name' => 'Mauritania', 'slug' => 'mauritania', 'phone_code' => '+222', 'iso_code' => 'MR'],
            ['name' => 'Gambia', 'slug' => 'gambia', 'phone_code' => '+220', 'iso_code' => 'GM'],
            ['name' => 'Guinea-Bissau', 'slug' => 'guinea-bissau', 'phone_code' => '+245', 'iso_code' => 'GW'],
            ['name' => 'Sierra Leone', 'slug' => 'sierra-leone', 'phone_code' => '+232', 'iso_code' => 'SL'],
            ['name' => 'Liberia', 'slug' => 'liberia', 'phone_code' => '+231', 'iso_code' => 'LR'],
            ['name' => 'Togo', 'slug' => 'togo', 'phone_code' => '+228', 'iso_code' => 'TG'],
            ['name' => 'Benin', 'slug' => 'benin', 'phone_code' => '+229', 'iso_code' => 'BJ'],
            ['name' => 'Samoa', 'slug' => 'samoa', 'phone_code' => '+685', 'iso_code' => 'WS'],
            ['name' => 'Tonga', 'slug' => 'tonga', 'phone_code' => '+676', 'iso_code' => 'TO'],
            ['name' => 'Vanuatu', 'slug' => 'vanuatu', 'phone_code' => '+678', 'iso_code' => 'VU'],
            ['name' => 'Solomon Islands', 'slug' => 'solomon-islands', 'phone_code' => '+677', 'iso_code' => 'SB'],
            ['name' => 'Kiribati', 'slug' => 'kiribati', 'phone_code' => '+686', 'iso_code' => 'KI'],
            ['name' => 'Tuvalu', 'slug' => 'tuvalu', 'phone_code' => '+688', 'iso_code' => 'TV'],
            ['name' => 'Nauru', 'slug' => 'nauru', 'phone_code' => '+674', 'iso_code' => 'NR'],
            ['name' => 'Palau', 'slug' => 'palau', 'phone_code' => '+680', 'iso_code' => 'PW'],
            ['name' => 'Micronesia', 'slug' => 'micronesia', 'phone_code' => '+691', 'iso_code' => 'FM'],
            ['name' => 'Marshall Islands', 'slug' => 'marshall-islands', 'phone_code' => '+692', 'iso_code' => 'MH'],
            ['name' => 'North Korea', 'slug' => 'north-korea', 'phone_code' => '+850', 'iso_code' => 'KP'],
            ['name' => 'Timor-Leste', 'slug' => 'timor-leste', 'phone_code' => '+670', 'iso_code' => 'TL'],
        ];


        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['slug' => $country['slug']],
                $country
            );
        }
    }
}
